import { useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useListBookings } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { EmptyState, AppHeader, SectionLabel, StatusPill } from '@/components/ui';
type BookingTab = 'upcoming' | 'completed' | 'cancelled';
export default function BookingsScreen() {
  const c = useColors(); const [tab, setTab] = useState<BookingTab>('upcoming'); const query = useListBookings({ vendorId: 1 }); const all = query.data ?? [];
  const filtered = all.filter(b => tab === 'upcoming' ? ['pending', 'confirmed'].includes(b.status) : b.status === tab);
  return <View style={[styles.screen, { backgroundColor: c.background }]}><FlatList data={filtered} keyExtractor={b => String(b.id)} refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => query.refetch()} tintColor={c.primary} />} contentContainerStyle={styles.content} ListHeaderComponent={<><AppHeader title="Bookings" subtitle="Keep every handover on track" /><View style={[styles.tabs, { backgroundColor: c.muted }]}>{(['upcoming', 'completed', 'cancelled'] as BookingTab[]).map(item => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && { backgroundColor: c.card }]}><Text style={[styles.tabText, { color: tab === item ? c.foreground : c.mutedForeground }]}>{item.charAt(0).toUpperCase() + item.slice(1)}</Text></Pressable>)}</View><View style={styles.listLabel}><SectionLabel>{filtered.length} {tab} {filtered.length === 1 ? 'booking' : 'bookings'}</SectionLabel></View></>} ListEmptyComponent={!query.isFetching ? <EmptyState icon="calendar" title={'No ' + tab + ' bookings'} message={tab === 'upcoming' ? 'New reservations will appear here.' : 'Bookings will move here when their status changes.'} /> : null} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/booking/[id]', params: { id: String(item.id) } })} style={({ pressed }) => [styles.card, { backgroundColor: c.card, borderColor: c.border, opacity: pressed ? 0.75 : 1 }]}><View style={[styles.iconBox, { backgroundColor: c.accent }]}><Feather name="calendar" size={20} color={c.primary} /></View><View style={styles.main}><View style={styles.row}><Text style={[styles.vehicle, { color: c.foreground }]}>{item.vehicleName || 'Vehicle booking'}</Text><StatusPill status={item.status} /></View><Text style={[styles.customer, { color: c.mutedForeground }]}>{item.userName || 'Customer'} · {item.rentalDays} {item.rentalDays === 1 ? 'day' : 'days'}</Text><View style={styles.details}><Text style={[styles.detail, { color: c.mutedForeground }]}><Feather name="calendar" size={12} color={c.mutedForeground} /> {new Date(item.pickupDate).toLocaleDateString()} – {new Date(item.returnDate).toLocaleDateString()}</Text><Text style={[styles.detail, { color: c.mutedForeground }]}><Feather name="map-pin" size={12} color={c.mutedForeground} /> {item.pickupLocation}</Text></View><Text style={[styles.total, { color: c.foreground }]}>{'$' + item.totalAmount.toLocaleString()} rental total</Text></View></Pressable>} /></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingBottom: 110 }, tabs: { flexDirection: 'row', padding: 4, borderRadius: 13, marginBottom: 24 }, tab: { flex: 1, borderRadius: 10, paddingVertical: 10, alignItems: 'center' }, tabText: { fontSize: 12, fontWeight: '700' }, listLabel: { marginBottom: 1 }, card: { borderWidth: 1, borderRadius: 18, padding: 15, flexDirection: 'row', gap: 12, marginBottom: 10 }, iconBox: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, main: { flex: 1 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, alignItems: 'flex-start' }, vehicle: { fontWeight: '700', fontSize: 15, flex: 1 }, customer: { fontSize: 12, marginTop: 4 }, details: { marginTop: 13, gap: 6 }, detail: { fontSize: 12 }, total: { fontSize: 13, fontWeight: '700', marginTop: 12 } });
