import { useMemo } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useGetVendor, useListBookings, useListVehicles } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { AppHeader, PrimaryButton, SectionLabel, StatusPill, styles as ui } from '@/components/ui';

export default function Dashboard() {
  const c = useColors(); const vendor = useGetVendor(1); const vehicles = useListVehicles({ vendorId: 1 }); const bookings = useListBookings({ vendorId: 1 });
  const list = vehicles.data ?? []; const allBookings = bookings.data ?? []; const upcoming = allBookings.filter(b => b.status !== 'cancelled' && b.status !== 'completed').slice(0, 3);
  const stats = useMemo(() => ({ total: list.length, available: list.filter(v => v.status === 'available').length, booked: list.filter(v => v.status === 'booked').length, unavailable: list.filter(v => v.status !== 'available' && v.status !== 'booked').length }), [list]);
  return <ScrollView style={[styles.screen, { backgroundColor: c.background }]} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={vehicles.isFetching || bookings.isFetching} onRefresh={() => { vehicles.refetch(); bookings.refetch(); }} tintColor={c.primary} />}>
    <AppHeader title={'Good morning, ' + (vendor.data?.contactName?.split(' ')[0] || 'there')} subtitle={vendor.data?.businessName || 'Your fleet at a glance'} action={<View style={[styles.online, { backgroundColor: c.successSoft }]}><View style={[styles.onlineDot, { backgroundColor: c.success }]} /><Text style={[styles.onlineText, { color: c.success }]}>Live</Text></View>} />
    <View style={styles.statGrid}>{[['truck', 'Vehicles', stats.total], ['check-circle', 'Available', stats.available], ['calendar', 'Booked', stats.booked], ['pause-circle', 'Unavailable', stats.unavailable]].map(([icon, label, value]) => <View key={String(label)} style={[styles.statCard, { backgroundColor: c.card, borderColor: c.border }]}><Feather name={icon as keyof typeof Feather.glyphMap} size={18} color={c.primary} /><Text style={[styles.statValue, { color: c.foreground }]}>{value}</Text><Text style={[styles.statLabel, { color: c.mutedForeground }]}>{label}</Text></View>)}</View>
    <View style={styles.sectionHead}><SectionLabel>Upcoming bookings</SectionLabel><Pressable onPress={() => router.push('/(tabs)/bookings')}><Text style={[styles.link, { color: c.primary }]}>See all</Text></Pressable></View>
    {upcoming.length === 0 ? <View style={[styles.emptyBooking, { backgroundColor: c.card, borderColor: c.border }]}><Feather name="calendar" size={24} color={c.mutedForeground} /><Text style={[styles.emptyTitle, { color: c.foreground }]}>No upcoming bookings</Text><Text style={[styles.emptyCopy, { color: c.mutedForeground }]}>New reservations will appear here.</Text></View> : upcoming.map(booking => <Pressable key={booking.id} onPress={() => router.push({ pathname: '/booking/[id]', params: { id: String(booking.id) } })} style={({ pressed }) => [styles.bookingCard, { backgroundColor: c.card, borderColor: c.border, opacity: pressed ? 0.75 : 1 }]}><View style={styles.bookingTop}><View><Text style={[styles.vehicleName, { color: c.foreground }]}>{booking.vehicleName || 'Vehicle booking'}</Text><Text style={[styles.customer, { color: c.mutedForeground }]}>{booking.userName || 'Customer'} · {booking.rentalDays} days</Text></View><StatusPill status={booking.status} /></View><View style={styles.bookingMeta}><Text style={[styles.meta, { color: c.mutedForeground }]}><Feather name="calendar" size={13} color={c.mutedForeground} /> {new Date(booking.pickupDate).toLocaleDateString()} – {new Date(booking.returnDate).toLocaleDateString()}</Text><Text style={[styles.meta, { color: c.mutedForeground }]}><Feather name="map-pin" size={13} color={c.mutedForeground} /> {booking.pickupLocation}</Text></View></Pressable>)}
    <View style={styles.actions}><PrimaryButton title="Add vehicle" icon="plus" onPress={() => router.push('/add-vehicle')} /><Pressable onPress={() => router.push('/(tabs)/vehicles')} style={[styles.secondaryAction, { backgroundColor: c.accent }]}><Feather name="sliders" size={17} color={c.accentForeground} /><Text style={[styles.secondaryText, { color: c.accentForeground }]}>Manage availability</Text></Pressable></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingTop: 8, paddingHorizontal: 20, paddingBottom: 110 }, online: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 99, paddingHorizontal: 9, paddingVertical: 6 }, onlineDot: { width: 6, height: 6, borderRadius: 9 }, onlineText: { fontSize: 11, fontWeight: '700' }, statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 28 }, statCard: { width: '48%', minHeight: 112, borderWidth: 1, borderRadius: 18, padding: 15, justifyContent: 'space-between' }, statValue: { fontSize: 30, fontWeight: '700', letterSpacing: -1 }, statLabel: { fontSize: 13, fontWeight: '600' }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, link: { fontSize: 13, fontWeight: '700', marginBottom: 10 }, bookingCard: { borderWidth: 1, borderRadius: 18, padding: 16, marginBottom: 10 }, bookingTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, vehicleName: { fontSize: 16, fontWeight: '700' }, customer: { fontSize: 13, marginTop: 4 }, bookingMeta: { borderTopWidth: 1, borderTopColor: 'transparent', marginTop: 15, gap: 8 }, meta: { fontSize: 12 }, emptyBooking: { borderWidth: 1, borderRadius: 18, padding: 24, alignItems: 'center', gap: 8, marginBottom: 18 }, emptyTitle: { fontWeight: '700', fontSize: 16 }, emptyCopy: { fontSize: 13 }, actions: { gap: 10, marginTop: 16 }, secondaryAction: { minHeight: 50, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, secondaryText: { fontSize: 15, fontWeight: '700' } });
