import { useCallback } from 'react';
import { FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useListVehicles } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { AppHeader, EmptyState, PrimaryButton, SectionLabel, StatusPill } from '@/components/ui';
export default function VehiclesScreen() {
  const c = useColors(); const query = useListVehicles({ vendorId: 1 });
  useFocusEffect(useCallback(() => { query.refetch(); }, []));
  const vehicles = query.data ?? [];
  return <View style={[styles.screen, { backgroundColor: c.background }]}><FlatList data={vehicles} keyExtractor={v => String(v.id)} refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => query.refetch()} tintColor={c.primary} />} contentContainerStyle={styles.content} ListHeaderComponent={<><AppHeader title="My vehicles" subtitle={vehicles.length + ' vehicles in your fleet'} action={<Pressable testID="add-vehicle-header" onPress={() => router.push('/add-vehicle')} style={[styles.headerAdd, { backgroundColor: c.accent }]}><Feather name="plus" size={18} color={c.accentForeground} /></Pressable>} /><SectionLabel>Fleet</SectionLabel></>} ListEmptyComponent={!query.isFetching ? <EmptyState icon="truck" title="No vehicles yet" message="Add your first vehicle to start receiving bookings." action={<PrimaryButton title="Add vehicle" icon="plus" onPress={() => router.push('/add-vehicle')} />} /> : null} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/vehicle/[id]', params: { id: String(item.id) } })} style={({ pressed }) => [styles.card, { backgroundColor: c.card, borderColor: c.border, opacity: pressed ? 0.75 : 1 }]}><View style={[styles.cardImage, { backgroundColor: c.muted }]}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.image} /> : <Feather name="truck" size={28} color={c.mutedForeground} />}</View><View style={styles.cardBody}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={[styles.name, { color: c.foreground }]}>{item.year} {item.make} {item.model}</Text><Text style={[styles.specs, { color: c.mutedForeground }]}>{item.transmission.charAt(0).toUpperCase() + item.transmission.slice(1)} · {item.seats} seats</Text></View><Text style={[styles.price, { color: c.foreground }]}>{'$' + item.pricePerDay}<Text style={[styles.per, { color: c.mutedForeground }]}>/day</Text></Text></View><View style={styles.cardBottom}><StatusPill status={item.status} /><Text style={[styles.manage, { color: c.primary }]}>Manage <Feather name="chevron-right" size={14} color={c.primary} /></Text></View></View></Pressable>} /></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingBottom: 110 }, headerAdd: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, card: { borderWidth: 1, borderRadius: 18, padding: 12, flexDirection: 'row', gap: 13, marginBottom: 11 }, cardImage: { width: 86, height: 86, borderRadius: 13, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }, image: { width: '100%', height: '100%' }, cardBody: { flex: 1, justifyContent: 'space-between', paddingVertical: 2 }, cardTop: { flexDirection: 'row', gap: 7 }, name: { fontWeight: '700', fontSize: 15, lineHeight: 20 }, specs: { fontSize: 12, marginTop: 4 }, price: { fontSize: 16, fontWeight: '700' }, per: { fontSize: 11, fontWeight: '500' }, cardBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13 }, manage: { fontSize: 12, fontWeight: '700' } });
