import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useGetBooking, useUpdateBooking } from '@workspace/api-client-react';
import { useColors } from '@/hooks/useColors';
import { PrimaryButton, SectionLabel, StatusPill } from '@/components/ui';
export default function BookingDetail() {
  const c = useColors(); const { id } = useLocalSearchParams<{ id: string }>(); const booking = useGetBooking(Number(id)); const update = useUpdateBooking(); const b = booking.data;
  if (!b) return <View style={[styles.loading, { backgroundColor: c.background }]}><Text style={{ color: c.mutedForeground }}>Loading booking…</Text></View>;
  const next = b.status === 'pending' ? 'confirmed' : b.status === 'confirmed' ? 'completed' : null;
  function advance() { if (!next || !b) return; Alert.alert('Update booking status?', next === 'confirmed' ? 'Confirm this booking and prepare the vehicle?' : 'Mark this rental as completed?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Update status', onPress: () => update.mutate({ id: b.id, data: { status: next } }, { onSuccess: () => booking.refetch() }) }]); }
  const rows = [['Vehicle', b.vehicleName || 'Vehicle'], ['Customer', b.userName || b.userPhone], ['Rental period', new Date(b.pickupDate).toLocaleDateString() + ' – ' + new Date(b.returnDate).toLocaleDateString()], ['Pick-up', b.pickupLocation], ['Rental total', '$' + b.totalAmount], ['QuickHire fee', '$' + b.bookingFee], ['Payable to vendor', '$' + (b.totalAmount - b.bookingFee)], ['Security deposit', '$' + b.securityDeposit + ' refundable']];
  return <ScrollView style={[styles.screen, { backgroundColor: c.background }]} contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()}><Feather name="arrow-left" size={23} color={c.foreground} /></Pressable><Text style={[styles.topTitle, { color: c.foreground }]}>Booking #{b.id}</Text><View style={{ width: 23 }} /></View><View style={[styles.summary, { backgroundColor: c.secondary }]}><Text style={[styles.summaryLabel, { color: c.secondaryForeground }]}>CURRENT STATUS</Text><Text style={[styles.vehicle, { color: c.secondaryForeground }]}>{b.vehicleName || 'Vehicle booking'}</Text><StatusPill status={b.status} /><Text style={[styles.summaryText, { color: c.secondaryForeground }]}>{b.rentalDays} {b.rentalDays === 1 ? 'day' : 'days'} · {'$' + b.totalAmount} total rental</Text></View><SectionLabel>Booking details</SectionLabel><View style={[styles.card, { backgroundColor: c.card, borderColor: c.border }]}>{rows.map((row, index) => <View key={row[0]} style={[styles.row, { borderBottomColor: c.border }, index === rows.length - 1 && styles.last]}><Text style={[styles.label, { color: c.mutedForeground }]}>{row[0]}</Text><Text style={[styles.value, { color: c.foreground }]}>{row[1]}</Text></View>)}</View>{next && <View style={styles.action}><PrimaryButton title={next === 'confirmed' ? 'Confirm & prepare vehicle' : 'Mark rental completed'} icon={next === 'confirmed' ? 'check-circle' : 'flag'} onPress={advance} loading={update.isPending} /></View>}<Text style={[styles.note, { color: c.mutedForeground }]}>Status changes are recorded immediately in QuickHire.</Text></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingBottom: 36 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, top: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, topTitle: { fontSize: 17, fontWeight: '700' }, summary: { borderRadius: 22, padding: 20, gap: 9, marginBottom: 27 }, summaryLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, opacity: 0.65 }, vehicle: { fontSize: 25, fontWeight: '700', letterSpacing: -0.7 }, summaryText: { fontSize: 13, opacity: 0.8 }, card: { borderWidth: 1, borderRadius: 18, overflow: 'hidden' }, row: { minHeight: 58, paddingHorizontal: 15, paddingVertical: 12, borderBottomWidth: 1, flexDirection: 'row', gap: 14, alignItems: 'center', justifyContent: 'space-between' }, last: { borderBottomWidth: 0 }, label: { fontSize: 13, flex: 1 }, value: { fontSize: 13, fontWeight: '700', flex: 1.2, textAlign: 'right' }, action: { marginTop: 22 }, note: { fontSize: 12, textAlign: 'center', marginTop: 14 } });
