import { useState } from 'react';
import { Keyboard, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { Field, Logo, PrimaryButton } from '@/components/ui';
import { useColors } from '@/hooks/useColors';

export default function LoginScreen() {
  const c = useColors(); const insets = useSafeAreaInsets();
  const [identity, setIdentity] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function login() { Keyboard.dismiss(); if (!identity.trim() || !password.trim()) { setError('Enter your mobile number or email and password.'); return; } setLoading(true); setError(''); await AsyncStorage.setItem('qh_vendor_session', 'active'); setTimeout(() => { setLoading(false); router.replace('/(tabs)'); }, 250); }
  return <View style={[styles.screen, { backgroundColor: c.background, paddingTop: insets.top + 26, paddingBottom: insets.bottom + 20 }]}><View style={styles.top}><Logo /><View style={[styles.badge, { backgroundColor: c.successSoft }]}><Feather name="shield" size={13} color={c.success} /><Text style={[styles.badgeText, { color: c.success }]}>Vendor portal</Text></View></View><View style={styles.hero}><Text style={[styles.kicker, { color: c.primary }]}>MANAGE ON THE MOVE</Text><Text style={[styles.title, { color: c.foreground }]}>Your fleet, in your pocket.</Text><Text style={[styles.body, { color: c.mutedForeground }]}>See bookings, update availability, and keep every car ready for its next customer.</Text></View><View style={[styles.form, { backgroundColor: c.card, borderColor: c.border }]}><Text style={[styles.formTitle, { color: c.foreground }]}>Vendor Login</Text><Field label="Mobile number or email" value={identity} onChangeText={setIdentity} autoCapitalize="none" keyboardType="email-address" placeholder="you@yourrental.co.zw" error={error} /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry placeholder="Enter your password" /><PrimaryButton title="Log in" icon="arrow-right" onPress={login} loading={loading} /><Pressable onPress={() => setError('Password reset will be available from your account support contact.')}><Text style={[styles.forgot, { color: c.primary }]}>Forgot password?</Text></Pressable></View><Text style={[styles.support, { color: c.mutedForeground }]}>Need an account? Contact QuickHire support.</Text></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: 20 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, badge: { flexDirection: 'row', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 99, alignItems: 'center' }, badgeText: { fontSize: 11, fontWeight: '700' }, hero: { paddingTop: 62, paddingBottom: 28 }, kicker: { fontSize: 11, fontWeight: '800', letterSpacing: 1.6, marginBottom: 12 }, title: { fontSize: 39, fontWeight: '700', lineHeight: 44, letterSpacing: -1.5 }, body: { fontSize: 16, lineHeight: 24, marginTop: 14, maxWidth: 340 }, form: { borderWidth: 1, borderRadius: 22, padding: 20 }, formTitle: { fontSize: 22, fontWeight: '700', marginBottom: 20 }, forgot: { textAlign: 'center', marginTop: 18, fontSize: 14, fontWeight: '600' }, support: { textAlign: 'center', fontSize: 13, marginTop: 20 } });
